### ISSUE TITLE
Running parser on a real PDF on Ubuntu crashes in decimal.Parse

### ISSUE THREAD

**Issue by arvesv** [arvesv/bankutskriftleser#1]
`
Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at Core.TrumfVisa.ParseTransaction(IEnumerator`1 enumerator) in D:\Skratch\bankutskriftleser\Core\TrumfVisa.cs:line 39
   at Core.TrumfVisa.ParseLine(IEnumerator`1 enumerator) in D:\Skratch\bankutskriftleser\Core\TrumfVisa.cs:line 27
   at Core.ParserBase.GetTransactions()+MoveNext() in D:\Skratch\bankutskriftleser\Core\ParserBase.cs:line 28
   at Parser.Program.Main(String[] args) in D:\Skratch\bankutskriftleser\Parser\Program.cs:line 32
Aborted (core dumped)
`

**Comment by arvesv** [comment]
This is probably caused by using the number formatting from the OS/user. Need to set this explicily. The unique thing about the number that causes crash is that it ha a space as a 1000 separator. " 1 261.72"

**Comment by arvesv** [comment]
A pull request was created by my change. It fixed the issue https://github.com/arvesv/bankutskriftleser/pull/2
